### PR TITLE
Icon picker with image button

### PR DESCRIPTION
**Pull request by codyfish**
Is this how you imagined it?
In order to align the image in some way I had to use Gtk.Box as halign didn't work as expected in the button. I added a property (`get_filename()`) to the button in order to keep the rest of the code, namely `serviceDialog.js` the same.
The code is still a little messy, I can clean it up if the results are as expected :D

### CODE REVIEW

**Comment by sonnyp** [comment]
@codyfish good start but I meant a square button with the image inside, without text/label. 

```js
  const image = new Image();
  if (value) {
    image.set_from_pixbuf(Pixbuf.new_from_file_at_scale(value, 28, 28, true));
  }
  const fileChooserButton = new Button({
    image,
  });
```

I understand why you added the label so that it would look good in the dialogs grid but the label gives no useful information to the user, here is what I propose:

Remove the label and in both `applicationDialog.js` and `serviceDialog.js` remove `iconLabel` and move `iconEntry` above the grid so that it is horizontally centered.

Something like:

```js
  // before contentArea.add(grid);
  const iconEntry = iconChooser({});
  const box = new Box({
    orientation: Orientation.HORIZONTAL,
    halign: Align.CENTER,
  });
  box.add(iconEntry);
  contentArea.add(box);
```

28x28 will be to small, also for application icons so I suggest 64/64


What do you think?

**Comment by codyfish** [comment]
A okay I see, I wasn't sure about the layout.

**Comment by codyfish** [comment]
I changed it. In order to see the icon at full resolution when re-editing a custom service I had to store the icon as 128x128 png. I still have to display default icons.

**Comment by sonnyp** [comment]
@codyfish do you mind if I have a look at/merge this first and do it in an other PR?

**Comment by codyfish** [comment]
No problem

**Comment by sonnyp** [comment]
closing for https://github.com/sonnyp/gigagram/pull/33

**Comment by sonnyp** [comment]
@codyfish Looks very nice!

Merged in https://github.com/sonnyp/gigagram/commit/361635e779f76b4fdcbe50a640b7fbffe430cf8d

I added the new icon picker to the application dialog and cleaned up a bit.

For your next PRs, do you think you could do this https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork ? Would make things easier as I could make some changes to your PRs without having to create a new branch.

If you feel like adding support for "default" icons, you're welcome to do so :)

**Comment by codyfish** [comment]
Yes, for sure I'll try to do that the next time.

**Pull request closed without merging**
