### PR TITLE
Header bar modified

### PR DESCRIPTION
**Pull request by mustafapc19**
Screenshot from 2019-07-20 11-42-15
Screenshot from 2019-07-20 11-41-55

 I think it is more consistent with Gnome. Especially using word "Add" with the icon is kinda clunky.

### CODE REVIEW

**Comment by sonnyp** [comment]
Did not know about GTK.Arrow, I just checked documentation and it says:

> GtkArrow has been deprecated; you can simply use a Gtk.Image with a
suitable icon name, such as “pan-down-symbolic“. When replacing
GtkArrow by an image, pay attention to the fact that GtkArrow is
doing automatic flipping between #GTK_ARROW_LEFT and #GTK_ARROW_RIGHT,
depending on the text direction. To get the same effect with an image,
use the icon names “pan-start-symbolic“ and “pan-end-symbolic“, which
react to the text direction.

https://gjs-docs.gnome.org/gtk30~3.24.8/gtk.arrow

Could you do that?

Regarding the label, agree.

**Comment by mustafapc19** [comment]
I'll look into to it.

**Comment by mustafapc19** [comment]
I have done the deed. See if it works on yours. I am still very noob in git.

**Comment by sonnyp** [comment]
looks better, thanks

**Comment by sonnyp** [comment]
these was a small issue with the menu button, I fixed it in https://github.com/sonnyp/gigagram/commit/7fa605bb2d58d428397b01bcd3312cc86b3e2769

**Comment by sonnyp** [comment]
Please feel free to add yourself to the list of contributors.
https://github.com/sonnyp/gigagram/edit/master/src/main.js#L66

**Pull request merged**
